-- ================================================================
-- APEXSALES CRM: SUPABASE SCHEMA & DATA MIGRATION
-- ================================================================

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public.leads (
  id TEXT PRIMARY KEY,
  name TEXT,
  company TEXT,
  status TEXT DEFAULT 'New',
  value NUMERIC DEFAULT 0,
  email TEXT,
  phone TEXT,
  source TEXT,
  score TEXT,
  next_follow_up TEXT,
  won_date TEXT,
  notes TEXT,
  owner TEXT DEFAULT 'Harsh Goyal',
  deal_type TEXT,
  previous_stage TEXT,
  stage_updated_at TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  raw_data JSONB
);

CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  name TEXT,
  display_name TEXT,
  username TEXT,
  pin TEXT,
  role TEXT,
  email TEXT,
  phone TEXT,
  active BOOLEAN DEFAULT true,
  package_tier TEXT,
  permissions JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id TEXT PRIMARY KEY,
  title TEXT,
  status TEXT DEFAULT 'pending',
  priority TEXT DEFAULT 'Medium',
  due_date TEXT,
  linked_lead_id TEXT,
  owner TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS) with open public access policies
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public full access to leads" ON public.leads;
CREATE POLICY "Allow public full access to leads" ON public.leads FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public full access to users" ON public.users;
CREATE POLICY "Allow public full access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public full access to tasks" ON public.tasks;
CREATE POLICY "Allow public full access to tasks" ON public.tasks FOR ALL USING (true) WITH CHECK (true);

-- 3. Clear existing initial data to prevent duplicates
DELETE FROM public.leads;
DELETE FROM public.users;

INSERT INTO public.users (id, name, display_name, username, pin, role, email, phone, active, package_tier, permissions)
VALUES ('usr_admin', 'Harsh Goyal', 'Harsh Goyal (Admin)', 'admin', '482910', 'admin', 'salesflowcrmhelp@gmail.com', '9876543210', true, '', '{}')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, permissions = EXCLUDED.permissions;
INSERT INTO public.users (id, name, display_name, username, pin, role, email, phone, active, package_tier, permissions)
VALUES ('usr_harsh', 'Harsh Goyal', 'Harsh Goyal (Admin)', 'harsh', '482910', 'admin', 'harsh.accomation@gmail.com', '9876543210', true, '', '{}')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, permissions = EXCLUDED.permissions;
INSERT INTO public.users (id, name, display_name, username, pin, role, email, phone, active, package_tier, permissions)
VALUES ('usr_1789033985345_n62j', 'Kashish', 'Kashish', 'kashish', 'Admin@123', 'sales_rep', 'Kashish.accomation@gmail.com', '7240705579', true, 'starter', '{"canViewKpiRevenue":true,"canViewKpiDeals":true,"canViewKpiConversion":true,"canViewKpiPipeline":true,"canViewFunnelStages":true,"canViewRevenuePacing":true,"canViewQuickActions":true,"canViewUpcomingFollowups":true,"canViewActivityFeed":true,"canViewTargetProgress":true,"canViewHotDealsRadar":true,"canViewClosingThisMonth":true,"canViewOverdueTasks":true,"canViewPipelineHealth":true,"canViewIncentiveEstimator":true,"canAccessPipeline":true,"canAccessDealsHub":true,"canAccessSplitView":true,"canAccessCalendar":true,"canAccessReports":false,"canAccessAnalytics":false,"canAccessAuditLogs":false,"canAccessSettings":false,"canAccessTeam":false,"canViewSpreadsheetGrid":true,"canViewKanbanDeals":true,"canViewSplitViewLayout":true,"canViewAnalyticsDashboard":true,"canViewAllLeads":false,"canCreateLeads":true,"canEditLeads":true,"canDeleteLeads":false,"canReassignLeads":false,"canChangeLeadScore":true,"canViewRevenue":true,"canEditDealValue":true,"canEditTarget":false,"canEditIncentive":false,"canExportCSV":false,"canBulkImport":false,"canSyncGoogleSheets":false,"canUseWhatsApp":true,"canMakeCalls":true,"canSendEmail":true,"canUseAI":true,"canUseAudioChimes":true}')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, role = EXCLUDED.role, permissions = EXCLUDED.permissions;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_arun_raval', 'Arun Raval', 'Direct Individual', 'Renewal Won', 6000, 'arunravalgst@gmail.com', '9033973907', 'Manual', 'Warm', '', '2026-09-05', 'Base + GST Renewal Won', 'Harsh Goyal', '', '', '{"id":"lead_arun_raval","name":"Arun Raval","company":"Direct Individual","status":"Renewal Won","value":6000,"email":"arunravalgst@gmail.com","phone":"9033973907","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-09-05","notes":"Base + GST Renewal Won","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_narendra_kumar', 'Narendra Kumar', 'Direct Individual', 'Won', 10000, '', '79069 50013', 'Manual', 'Warm', '', '2026-09-02', 'Base ₹8,475 + GST ₹1,525', 'Harsh Goyal', '', '', '{"id":"lead_narendra_kumar","name":"Narendra Kumar","company":"Direct Individual","status":"Won","value":10000,"email":"","phone":"79069 50013","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-09-02","notes":"Base ₹8,475 + GST ₹1,525","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_jaideep', 'Jaideep', 'Direct Individual', 'Won', 12500, '', '75759 62997', 'Manual', 'Warm', '', '2026-08-29', 'Base ₹10,593 + GST ₹1,907', 'Harsh Goyal', '', '', '{"id":"lead_jaideep","name":"Jaideep","company":"Direct Individual","status":"Won","value":12500,"email":"","phone":"75759 62997","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-29","notes":"Base ₹10,593 + GST ₹1,907","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_lokendra_singh', 'Lokendra Singh', 'Direct Individual', 'Won', 12000, 'solankisingh97@gmail.com', '91666 43493', 'Manual', 'Warm', '', '2026-08-22', 'Base ₹10,169 + GST ₹1,831', 'Harsh Goyal', '', '', '{"id":"lead_lokendra_singh","name":"Lokendra Singh","company":"Direct Individual","status":"Won","value":12000,"email":"solankisingh97@gmail.com","phone":"91666 43493","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-22","notes":"Base ₹10,169 + GST ₹1,831","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_amol_singh', 'Amol Singh', 'Trolltech', 'Won', 12000, 'amolsingh@trolltech.co.in', '98710 87005', 'Manual', 'Warm', '', '2026-08-19', 'Base ₹10,169 + GST ₹1,831', 'Harsh Goyal', '', '', '{"id":"lead_amol_singh","name":"Amol Singh","company":"Trolltech","status":"Won","value":12000,"email":"amolsingh@trolltech.co.in","phone":"98710 87005","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-19","notes":"Base ₹10,169 + GST ₹1,831","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_mohammed_imran', 'Mohammed Imran', 'MICORPS', 'Won', 6000, 'Mdimran.micorps@gmail.com', '9741599107', 'Manual', 'Warm', '', '2026-08-07', 'Full payment received', 'Harsh Goyal', '', '', '{"id":"lead_mohammed_imran","name":"Mohammed Imran","company":"MICORPS","status":"Won","value":6000,"email":"Mdimran.micorps@gmail.com","phone":"9741599107","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-07","notes":"Full payment received","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_arvind_pawar', 'Arvind Pawar', 'Tax Plus Consultancy', 'Won', 7000, 'taxplusconsultancy@gmail.com', '7798680780', 'Manual', 'Warm', '', '2026-08-06', 'Consultancy license closed', 'Harsh Goyal', '', '', '{"id":"lead_arvind_pawar","name":"Arvind Pawar","company":"Tax Plus Consultancy","status":"Won","value":7000,"email":"taxplusconsultancy@gmail.com","phone":"7798680780","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-06","notes":"Consultancy license closed","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_vinay_shridhar', 'Vinay Shridhar', 'Matins Healthcare', 'Won', 11000, 'matinshealthcare@gmail.com', '9810121951', 'Manual', 'Warm', '', '2026-08-05', 'Annual plan won', 'Harsh Goyal', '', '', '{"id":"lead_vinay_shridhar","name":"Vinay Shridhar","company":"Matins Healthcare","status":"Won","value":11000,"email":"matinshealthcare@gmail.com","phone":"9810121951","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-05","notes":"Annual plan won","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_lingraj', 'Lingraj R N', 'Lingaraj RN & Co', 'Won', 8000, 'lingarajrn.co@gmail.com', '7795743411', 'Manual', 'Warm', '', '2026-08-08', 'Single company license', 'Harsh Goyal', '', '', '{"id":"lead_lingraj","name":"Lingraj R N","company":"Lingaraj RN & Co","status":"Won","value":8000,"email":"lingarajrn.co@gmail.com","phone":"7795743411","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-08","notes":"Single company license","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_sanjeev_mali', 'Sanjeev Mali', 'Direct Individual', 'Won', 10000, 'sanjeevmali1971@gmail.com', '9886871546', 'Manual', 'Warm', '', '2026-08-08', 'Closed won deal', 'Harsh Goyal', '', '', '{"id":"lead_sanjeev_mali","name":"Sanjeev Mali","company":"Direct Individual","status":"Won","value":10000,"email":"sanjeevmali1971@gmail.com","phone":"9886871546","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-08","notes":"Closed won deal","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_hetul', 'Hetul sanghvi', 'Direct Individual', 'Renewal Won', 10000, 'hetuljsanghvi@gmail.com', '9898113331', 'Manual', 'Warm', '', '2026-09-02', '15k+GST', 'Harsh Goyal', 'new', 'Won', '{"id":"lead_hetul","name":"Hetul sanghvi","company":"Direct Individual","status":"Renewal Won","value":10000,"email":"hetuljsanghvi@gmail.com","phone":"9898113331","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-09-02","notes":"15k+GST","owner":"Harsh Goyal","deal_type":"new","previous_stage":"Won","stageUpdatedAt":"2026-09-14T12:02:19.064Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_modi', 'Kalpesh Modi', 'DK Modi & Co', 'Lost', 15000, 'dkmodico@gmail.com', '9925004405', 'Manual', 'Warm', '2026-09-20', '2026-09-09', '20 ko payment kre ga', 'Harsh Goyal', '', '', '{"id":"lead_modi","name":"Kalpesh Modi","company":"DK Modi & Co","status":"Lost","value":15000,"email":"dkmodico@gmail.com","phone":"9925004405","source":"Manual","score":"Warm","next_follow_up":"2026-09-20","won_date":"2026-09-09","notes":"20 ko payment kre ga","owner":"Harsh Goyal","stageUpdatedAt":"2026-09-14T06:36:15.052Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_anubhav', 'Anubhav Agarwal', 'Direct Individual', 'Lost', 15000, 'anubhavagrawal82@gmail.com', '+91 98189 30423', 'Manual', 'Hot', '', '2026-08-28', '15k+GST for 5 co. | 9910158681 Santosh', 'Harsh Goyal', '', '', '{"id":"lead_anubhav","name":"Anubhav Agarwal","company":"Direct Individual","status":"Lost","value":15000,"email":"anubhavagrawal82@gmail.com","phone":"+91 98189 30423","source":"Manual","score":"Hot","next_follow_up":"","won_date":"2026-08-28","notes":"15k+GST for 5 co. | 9910158681 Santosh","owner":"Harsh Goyal","stageUpdatedAt":"2026-09-14T06:36:09.412Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_sanjjay', 'Sanjjay Bablani', 'UGPL', 'Lost', 15000, 'ugpl2011@gmail.com', '+91 99101 75554', 'Manual', 'Hot', '', '2026-08-20', '15k+GST for unlimited co.', 'Harsh Goyal', '', '', '{"id":"lead_sanjjay","name":"Sanjjay Bablani","company":"UGPL","status":"Lost","value":15000,"email":"ugpl2011@gmail.com","phone":"+91 99101 75554","source":"Manual","score":"Hot","next_follow_up":"","won_date":"2026-08-20","notes":"15k+GST for unlimited co.","owner":"Harsh Goyal","stageUpdatedAt":"2026-09-14T06:35:16.940Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_ramnath', 'Ramnath Kumar', 'Direct Individual', 'Won', 8000, 'ramkumar31555@gmail.com', '919615222555', 'Manual', 'Hot', '', '2026-08-19', '1-2 days mai batye ga offer k liye puch rha tha', 'Harsh Goyal', '', '', '{"id":"lead_ramnath","name":"Ramnath Kumar","company":"Direct Individual","status":"Won","value":8000,"email":"ramkumar31555@gmail.com","phone":"919615222555","source":"Manual","score":"Hot","next_follow_up":"","won_date":"2026-08-19","notes":"1-2 days mai batye ga offer k liye puch rha tha","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_prashant', 'Prashant Gautam', 'Direct Individual', 'Won', 10000, 'prashantgautam903@gmail.com', '+919887554903', 'Manual', 'Warm', '', '2026-08-08', '10k+GST 5 co. 15k+GST unlimited co.', 'Harsh Goyal', '', '', '{"id":"lead_prashant","name":"Prashant Gautam","company":"Direct Individual","status":"Won","value":10000,"email":"prashantgautam903@gmail.com","phone":"+919887554903","source":"Manual","score":"Warm","next_follow_up":"","won_date":"2026-08-08","notes":"10k+GST 5 co. 15k+GST unlimited co.","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_amit_miglani', 'Amit Miglani', 'Direct Individual', 'Won', 10000, 'miglanikamit@gmail.com', '98120 69041', 'Manual', 'Warm', '', '2026-09-17', 'Payment follow-up pending. Review invoice terms for ₹10,000-₹15,000.', 'Harsh Goyal', 'new', 'Payment Follow Up', '{"id":"lead_amit_miglani","name":"Amit Miglani","company":"Direct Individual","status":"Won","value":10000,"email":"miglanikamit@gmail.com","phone":"98120 69041","source":"Manual","score":"Warm","next_follow_up":"","notes":"Payment follow-up pending. Review invoice terms for ₹10,000-₹15,000.","owner":"Harsh Goyal","deal_type":"new","previous_stage":"Payment Follow Up","stageUpdatedAt":"2026-09-17T04:56:11.844Z","won_date":"2026-09-17"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_anshul_lodha', 'Anshul Lodha', 'Meridian Associates', 'Renewal', 7000, 'meridianassociate2019@gmail.com', '9820892128', 'Manual', 'Warm', '2026-09-02', '', 'Renewal contract discussion', 'Harsh Goyal', '', '', '{"id":"lead_anshul_lodha","name":"Anshul Lodha","company":"Meridian Associates","status":"Renewal","value":7000,"email":"meridianassociate2019@gmail.com","phone":"9820892128","source":"Manual","score":"Warm","next_follow_up":"2026-09-02","notes":"Renewal contract discussion","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_surabhi', 'Surabhi', 'Direct Individual', 'Payment Follow Up', 7000, '', '', 'Manual', 'Warm', '2026-08-26', '', 'Payment follow up pending', 'Harsh Goyal', '', '', '{"id":"lead_surabhi","name":"Surabhi","company":"Direct Individual","status":"Payment Follow Up","value":7000,"email":"","phone":"","source":"Manual","score":"Warm","next_follow_up":"2026-08-26","notes":"Payment follow up pending","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_ssivaa', 'SSivaa Kumaarr', 'Direct Individual', 'Demo Done', 15000, 'msivak99@gmail.com', '+91 97032 92929', 'Manual', 'Warm', '2026-08-23', '', 'Demo completed. Awaiting final decision.', 'Harsh Goyal', '', '', '{"id":"lead_ssivaa","name":"SSivaa Kumaarr","company":"Direct Individual","status":"Demo Done","value":15000,"email":"msivak99@gmail.com","phone":"+91 97032 92929","source":"Manual","score":"Warm","next_follow_up":"2026-08-23","notes":"Demo completed. Awaiting final decision.","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_suman_saha', 'SUMAN SAHA', 'Maxx Solutions', 'Demo Done', 5000, 'sumanmaxx@gmail.com', '9831094835', 'Manual', 'Warm', '2026-09-01', '', 'Demo finished. Commercial discussion in progress.', 'Harsh Goyal', '', '', '{"id":"lead_suman_saha","name":"SUMAN SAHA","company":"Maxx Solutions","status":"Demo Done","value":5000,"email":"sumanmaxx@gmail.com","phone":"9831094835","source":"Manual","score":"Warm","next_follow_up":"2026-09-01","notes":"Demo finished. Commercial discussion in progress.","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_juned', 'Juned Malkani', 'Direct Individual', 'Negotiation', 20000, 'sumalkani@gmail.com', '9428730989', 'Referral', 'Warm', '2026-09-10', '', 'Commercial quote shared, in negotiation', 'Harsh Goyal', '', '', '{"id":"lead_juned","name":"Juned Malkani","company":"Direct Individual","status":"Negotiation","value":20000,"email":"sumalkani@gmail.com","phone":"9428730989","source":"Referral","score":"Warm","next_follow_up":"2026-09-10","notes":"Commercial quote shared, in negotiation","owner":"Harsh Goyal","updatedAt":"2026-09-10T12:14:04.927Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_chetan', 'Chetan Agarwal', 'Direct Individual', 'Qualified', 15000, 'chetanlko1@gmail.com', '7275061154', 'Manual', 'Hot', '2026-09-11', '', 'Qualified lead', 'Harsh Goyal', '', '', '{"id":"lead_chetan","name":"Chetan Agarwal","company":"Direct Individual","status":"Qualified","value":15000,"email":"chetanlko1@gmail.com","phone":"7275061154","source":"Manual","score":"Hot","next_follow_up":"2026-09-11","notes":"Qualified lead","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_kalpesh_p', 'Kalpesh Panchal', 'Direct Individual', 'Contacted', 10000, 'kalpeshpanchal47@gmail.com', '9898818993', 'Manual', 'Warm', '2026-09-12', '', 'Initial pitch completed', 'Harsh Goyal', '', '', '{"id":"lead_kalpesh_p","name":"Kalpesh Panchal","company":"Direct Individual","status":"Contacted","value":10000,"email":"kalpeshpanchal47@gmail.com","phone":"9898818993","source":"Manual","score":"Warm","next_follow_up":"2026-09-12","notes":"Initial pitch completed","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_dipti', 'Dipti Shah', 'Direct Individual', 'Renewal', 12000, 'diptishah567@rediffmail.com', '9687604578', 'Manual', 'Warm', '2026-09-14', '', 'Renewal upcoming', 'Harsh Goyal', '', '', '{"id":"lead_dipti","name":"Dipti Shah","company":"Direct Individual","status":"Renewal","value":12000,"email":"diptishah567@rediffmail.com","phone":"9687604578","source":"Manual","score":"Warm","next_follow_up":"2026-09-14","notes":"Renewal upcoming","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_alok', 'Alok Kumar Gothi', 'IMP Details', 'Proposal Sent', 18000, 'impgothidetails@gmail.com', '+91 96254 52224', 'Manual', 'Hot', '2026-09-10', '', 'Proposal dispatched', 'Harsh Goyal', '', '', '{"id":"lead_alok","name":"Alok Kumar Gothi","company":"IMP Details","status":"Proposal Sent","value":18000,"email":"impgothidetails@gmail.com","phone":"+91 96254 52224","source":"Manual","score":"Hot","next_follow_up":"2026-09-10","notes":"Proposal dispatched","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_nitin', 'Nitin Jain', 'Direct Individual', 'Contacted', 10000, '', '9646541244', 'Manual', 'Hot', '2026-09-10', '', 'Follow up scheduled', 'Harsh Goyal', '', '', '{"id":"lead_nitin","name":"Nitin Jain","company":"Direct Individual","status":"Contacted","value":10000,"email":"","phone":"9646541244","source":"Manual","score":"Hot","next_follow_up":"2026-09-10","notes":"Follow up scheduled","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_ansari', 'Ansari Nurul Huda', 'Direct Individual', 'Qualified', 12000, 'annu24aug@yahoo.com', '919837450608', 'Manual', 'Warm', '2026-09-11', '', 'Requirements gathering', 'Harsh Goyal', '', '', '{"id":"lead_ansari","name":"Ansari Nurul Huda","company":"Direct Individual","status":"Qualified","value":12000,"email":"annu24aug@yahoo.com","phone":"919837450608","source":"Manual","score":"Warm","next_follow_up":"2026-09-11","notes":"Requirements gathering","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_ashok', 'Ashok Kumar', 'Direct Individual', 'Proposal Sent', 15000, 'ak80980@gmail.com', '+91 96900 14241', 'Manual', 'Warm', '2026-09-12', '', 'Proposal sent', 'Harsh Goyal', '', '', '{"id":"lead_ashok","name":"Ashok Kumar","company":"Direct Individual","status":"Proposal Sent","value":15000,"email":"ak80980@gmail.com","phone":"+91 96900 14241","source":"Manual","score":"Warm","next_follow_up":"2026-09-12","notes":"Proposal sent","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_import_1789038270816_0_3qso', 'Rajesh Sharma Test', 'TechCorp Solutions', 'New', 25000, 'rajesh@techcorp.in', '9876543210', 'Website', 'Hot', '', '', 'Sample lead import test', 'Harsh Goyal', '', '', '{"id":"lead_import_1789038270816_0_3qso","name":"Rajesh Sharma Test","company":"TechCorp Solutions","status":"New","value":25000,"email":"rajesh@techcorp.in","phone":"9876543210","source":"Website","score":"Hot","next_follow_up":"","notes":"Sample lead import test","owner":"Harsh Goyal","createdAt":"2026-09-10T11:04:30.816Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_neha_sen', 'Neha Sen', 'Sen Consultancy', 'Lost', 24000, 'neha.sen@corp.com', '+91 8888822222', 'Website', 'Cold', '', '', 'Client postponed budget - closed lost', 'Harsh Goyal', '', '', '{"id":"lead_neha_sen","name":"Neha Sen","company":"Sen Consultancy","status":"Lost","value":24000,"email":"neha.sen@corp.com","phone":"+91 8888822222","source":"Website","score":"Cold","next_follow_up":"","notes":"Client postponed budget - closed lost","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_rahul_verma', 'Rahul Verma', 'Verma Logistics', 'Lost', 15000, 'rahul@vermalogistics.in', '+91 9999911111', 'Cold Call', 'Cold', '', '', 'Went with competitor solution', 'Harsh Goyal', '', '', '{"id":"lead_rahul_verma","name":"Rahul Verma","company":"Verma Logistics","status":"Lost","value":15000,"email":"rahul@vermalogistics.in","phone":"+91 9999911111","source":"Cold Call","score":"Cold","next_follow_up":"","notes":"Went with competitor solution","owner":"Harsh Goyal"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383913646', 'Dipak Thakkar', '', 'Won', 5000, 'dipak3103@hotmail.com', '+91 97277 01626', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Harsh Goyal', 'new', 'Demo Done', '{"id":"lead_1789383913646","activities":[{"id":"act_1789383913646","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-14T11:05:13.646Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"dipak3103@hotmail.com","name":"Dipak Thakkar","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Harsh Goyal","phone":"+91 97277 01626","score":"Warm","source":"Manual","status":"Won","value":5000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:07:53.940Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789381402327', 'Raj patel', '', 'Won', 15000, 'info@rpaca.in', '94287 11407', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789381402327","activities":[{"id":"act_1789381507954_3ikm","type":"whatsapp","title":"WhatsApp Chat Opened","desc":"Initiated WhatsApp follow-up with Raj patel","timestamp":"2026-09-14T10:25:07.954Z","performedBy":"Kashish"},{"id":"act_1789381502809_7uyp","type":"call","title":"Call Dialed","desc":"Dialed call to Raj patel (94287 11407)","timestamp":"2026-09-14T10:25:02.809Z","performedBy":"Kashish"},{"id":"act_1789381492147_086x","type":"email","title":"Email Client Opened","desc":"Opened email to Raj patel (info@rpaca.in)","timestamp":"2026-09-14T10:24:52.147Z","performedBy":"Kashish"},{"id":"act_1789381402327","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T10:23:22.327Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"info@rpaca.in","name":"Raj patel","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"94287 11407","score":"Warm","source":"Manual","status":"Won","value":15000,"lastActivityAt":"2026-09-14T10:25:07.954Z","deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T10:26:42.794Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789381475433', 'CA Anil Dantani', '', 'Lost', 15000, '', '93270 98589', 'Manual', 'Warm', '2026-09-16', '2026-09-14', 'payment lena hai bs, pricing shared 15k 25k 30k
---
Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Won', '{"id":"lead_1789381475433","activities":[{"id":"act_1789712376902_96mc","type":"stage_change","title":"Deal Closed Lost","desc":"Marked deal as Lost.","timestamp":"2026-09-18T06:19:36.902Z","performedBy":"Kashish"},{"id":"act_1789381599139_jrj5","type":"stage_change","title":"Deal Stage Changed","desc":"Moved from \"Won\" to \"Demo Done\" (Deal Value: ₹15,000)","timestamp":"2026-09-14T10:26:39.140Z","performedBy":"Kashish"},{"id":"act_1789381599137","type":"stage_update","text":"Moved from Won to Demo Done. Notes: \"payment lena hai bs, pricing shared 15k 25k 30k\"","createdAt":"2026-09-14T10:26:39.137Z"},{"id":"act_1789381475433","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T10:24:35.433Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"","name":"CA Anil Dantani","next_follow_up":"2026-09-16","next_follow_up_time":"","notes":"payment lena hai bs, pricing shared 15k 25k 30k\n---\nProduct demo completed. Client showed positive interest.","owner":"Kashish","phone":"93270 98589","score":"Warm","source":"Manual","status":"Lost","value":15000,"deal_type":"new","previous_stage":"Won","stageUpdatedAt":"2026-09-18T06:19:36.900Z","won_date":"2026-09-14","follow_up_time":"10:00","lastActivityAt":"2026-09-18T06:19:36.902Z","updatedAt":"2026-09-14T10:26:39.536Z"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383775529', 'Deepak Khatri', '', 'Won', 8000, '', '94252 58247', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789383775529","activities":[{"id":"act_1789383775529","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:02:55.529Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"","name":"Deepak Khatri","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"94252 58247","score":"Warm","source":"Manual","status":"Won","value":8000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:08:24.112Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383806401', 'Raghavendra', '', 'Won', 13000, '', '99647 67276', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789383806401","activities":[{"id":"act_1789383806401","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:03:26.401Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"","name":"Raghavendra","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"99647 67276","score":"Warm","source":"Manual","status":"Won","value":13000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:08:20.271Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383996869', 'Prashanth', '', 'Won', 18000, 'knp.prashanth@gmail.com', '+91 97395 16001', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Harsh Goyal', 'new', 'Demo Done', '{"id":"lead_1789383996869","activities":[{"id":"act_1789383996869","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-14T11:06:36.869Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"knp.prashanth@gmail.com","name":"Prashanth","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Harsh Goyal","phone":"+91 97395 16001","score":"Warm","source":"Manual","status":"Won","value":18000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:07:50.183Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789384053622', 'Sandip Lokhande', '', 'Won', 6000, 'yogayogagro11@gmail.com', '+91 88052 55566', 'Manual', 'Warm', '', '2026-09-14', 'New lead added to pipeline. Follow-up scheduled.', 'Harsh Goyal', 'new', 'New', '{"id":"lead_1789384053622","activities":[{"id":"act_1789384053622","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-14T11:07:33.622Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"yogayogagro11@gmail.com","name":"Sandip Lokhande","next_follow_up":"","next_follow_up_time":"","notes":"New lead added to pipeline. Follow-up scheduled.","owner":"Harsh Goyal","phone":"+91 88052 55566","score":"Warm","source":"Manual","status":"Won","value":6000,"deal_type":"new","previous_stage":"New","stageUpdatedAt":"2026-09-14T11:07:43.439Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383835992', 'sushil Batra', '', 'Won', 5000, 'designculturenagpur@gmail.com', '9893779000', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789383835992","activities":[{"id":"act_1789383835992","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:03:55.992Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"designculturenagpur@gmail.com","name":"sushil Batra","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"9893779000","score":"Warm","source":"Manual","status":"Won","value":5000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:08:17.312Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383885425', 'Knvs Sarma', '', 'Won', 13000, 'ceo@yasaswifinserve.com', '98482 58834', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789383885425","activities":[{"id":"act_1789383885425","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:04:45.425Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"ceo@yasaswifinserve.com","name":"Knvs Sarma","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"98482 58834","score":"Warm","source":"Manual","status":"Won","value":13000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:08:13.136Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789383953535', 'Vivek Kumar', '', 'Won', 25000, 'it@futurevalue.in', '85953 37973', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789383953535","activities":[{"id":"act_1789383953535","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:05:53.535Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"it@futurevalue.in","name":"Vivek Kumar","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"85953 37973","score":"Warm","source":"Manual","status":"Won","value":25000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:08:10.359Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789384011169', 'Jitendra ji â€”Delhi', '', 'Won', 10000, '', '93122 12305', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789384011169","activities":[{"id":"act_1789384011169","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:06:51.169Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"","name":"Jitendra ji â€”Delhi","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"93122 12305","score":"Warm","source":"Manual","status":"Won","value":10000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T11:08:05.521Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789384066529', 'Gopikrishna Mallireddy', '', 'Won', 13000, '', '94825 12223', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Kashish', 'new', 'Demo Done', '{"id":"lead_1789384066529","activities":[{"id":"act_1789384066529","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Kashish.","timestamp":"2026-09-14T11:07:46.529Z","performedBy":"Kashish"}],"company":"","custom_fields":{},"email":"","name":"Gopikrishna Mallireddy","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Kashish","phone":"94825 12223","score":"Warm","source":"Manual","status":"Won","value":13000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T12:15:57.157Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789387993439', 'Ashok Kumar', '', 'Won', 7000, 'ak80980@gmail.com', '+91 96900 14241', 'Manual', 'Warm', '', '2026-09-14', 'Product demo completed. Client showed positive interest.', 'Harsh Goyal', 'new', 'Demo Done', '{"id":"lead_1789387993439","activities":[{"id":"act_1789387993439","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-14T12:13:13.439Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"ak80980@gmail.com","name":"Ashok Kumar","next_follow_up":"","next_follow_up_time":"","notes":"Product demo completed. Client showed positive interest.","owner":"Harsh Goyal","phone":"+91 96900 14241","score":"Warm","source":"Manual","status":"Won","value":7000,"deal_type":"new","previous_stage":"Demo Done","stageUpdatedAt":"2026-09-14T12:13:26.493Z","won_date":"2026-09-14"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789817705320', 'Chintan Agrawal', '', 'Payment Follow Up', 10000, 'agrawal.chintan05@gmail.com', '918435542500', 'Google Ads', 'Warm', '2026-09-19', '', 'Payment follow-up active. Client promised payment for 19 Sept.', 'Harsh Goyal', '', '', '{"id":"lead_1789817705320","activities":[{"id":"act_1789817705320","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-19T11:35:05.320Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"agrawal.chintan05@gmail.com","name":"Chintan Agrawal","next_follow_up":"2026-09-19","next_follow_up_time":"11:00 AM","notes":"Payment follow-up active. Client promised payment for 19 Sept.","owner":"Harsh Goyal","packageId":"pkg_silver","phone":"918435542500","score":"Warm","source":"Google Ads","status":"Payment Follow Up","value":10000}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789818687592', 'Tushar Thakkar', '', 'Payment Follow Up', 11000, 'trthakkar@gmail.com', '919737003111', 'Facebook', 'Warm', '2026-09-21', '', 'demo done payment follow up', 'Harsh Goyal', '', '', '{"id":"lead_1789818687592","activities":[{"id":"act_1789818687593","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-19T11:51:27.593Z","performedBy":"Harsh Goyal"},{"id":"act_note_1789818687593","type":"note","title":"Initial Note Added","desc":"demo done payment follow up","timestamp":"2026-09-19T11:51:27.593Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"trthakkar@gmail.com","name":"Tushar Thakkar","next_follow_up":"2026-09-21","next_follow_up_time":"11:00 AM","notes":"demo done payment follow up","owner":"Harsh Goyal","packageId":"","phone":"919737003111","score":"Warm","source":"Facebook","status":"Payment Follow Up","value":11000}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789818827047', 'vikas chougule', '', 'Payment Follow Up', 6000, 'shreemahalaxmiagrotec555@gmail.com', '917030547555', 'Facebook', 'Warm', '2026-09-21', '', 'demo done payment follow up', 'Harsh Goyal', '', '', '{"id":"lead_1789818827047","activities":[{"id":"act_1789818827047","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-19T11:53:47.047Z","performedBy":"Harsh Goyal"},{"id":"act_note_1789818827047","type":"note","title":"Initial Note Added","desc":"demo done payment follow up","timestamp":"2026-09-19T11:53:47.047Z","performedBy":"Harsh Goyal"}],"company":"","custom_fields":{},"email":"shreemahalaxmiagrotec555@gmail.com","name":"vikas chougule","next_follow_up":"2026-09-21","next_follow_up_time":"11:00 AM","notes":"demo done payment follow up","owner":"Harsh Goyal","packageId":"","phone":"917030547555","score":"Warm","source":"Facebook","status":"Payment Follow Up","value":6000}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789819063408', 'deepak', '', 'Payment Follow Up', 10000, 'deepakmanwani960@gmail.com', '918104681341', 'Facebook', 'Warm', '2026-09-21', '', 'demo done payment follow up', 'Harsh Goyal', '', '', '{"id":"lead_1789819063408","name":"deepak","company":"","status":"Payment Follow Up","value":10000,"packageId":"","email":"deepakmanwani960@gmail.com","phone":"918104681341","source":"Facebook","score":"Warm","owner":"Harsh Goyal","next_follow_up":"2026-09-21","next_follow_up_time":"11:00 AM","custom_fields":{},"activities":[{"id":"act_1789819063408","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-19T11:57:43.408Z","performedBy":"Harsh Goyal"},{"id":"act_note_1789819063408","type":"note","title":"Initial Note Added","desc":"demo done payment follow up","timestamp":"2026-09-19T11:57:43.408Z","performedBy":"Harsh Goyal"}],"notes":"demo done payment follow up"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
INSERT INTO public.leads (id, name, company, status, value, email, phone, source, score, next_follow_up, won_date, notes, owner, deal_type, previous_stage, raw_data)
VALUES ('lead_1789819261967', 'Kiran shinde', '', 'Payment Follow Up', 15000, 'kirankshindeandco@gmail.com', '+91 75066 47791', 'Google Ads', 'Warm', '2026-10-01', '', 'demo done 1 oct ko connect krna hai', 'Harsh Goyal', '', '', '{"id":"lead_1789819261967","name":"Kiran shinde","company":"","status":"Payment Follow Up","value":15000,"packageId":"","email":"kirankshindeandco@gmail.com","phone":"+91 75066 47791","source":"Google Ads","score":"Warm","owner":"Harsh Goyal","next_follow_up":"2026-10-01","next_follow_up_time":"11:00 AM","custom_fields":{},"activities":[{"id":"act_1789819261967","type":"created","title":"Lead Created","desc":"Lead added to pipeline and assigned to Harsh Goyal.","timestamp":"2026-09-19T12:01:01.967Z","performedBy":"Harsh Goyal"},{"id":"act_note_1789819261967","type":"note","title":"Initial Note Added","desc":"demo done 1 oct ko connect krna hai","timestamp":"2026-09-19T12:01:01.967Z","performedBy":"Harsh Goyal"}],"notes":"demo done 1 oct ko connect krna hai"}')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, next_follow_up = EXCLUDED.next_follow_up, won_date = EXCLUDED.won_date, owner = EXCLUDED.owner;
